use `e-commerce`;
SELECT * FROM `e-commerce`.customer_shopping_trends;

# Business insights
#1. Total revenue generated by male vs Female customers
SELECT gender, sum(purchase_amount) as revenue FROM `e-commerce`.customer_shopping_trends group by gender;

#2. Even though promo code applied, purchase amount > average purchase
SELECT customer_id, age_group, frequency_of_purchase_days, purchase_amount FROM `e-commerce`.customer_shopping_trends where discount_applied = "Yes" and purchase_amount > (SELECT round(avg(purchase_amount),2) FROM `e-commerce`.customer_shopping_trends);

#3. Top 5 products with highest average review rating
SELECT item_purchased, round(avg(review_rating),2) as average_review_rating FROM `e-commerce`.customer_shopping_trends group by item_purchased order by round(avg(review_rating),2) desc limit 5;

#4. Average purchase amount based on shipping type
SELECT shipping_type ,round(avg(purchase_amount),2) as average_purchase_amount FROM `e-commerce`.customer_shopping_trends group by shipping_type order by round(avg(purchase_amount),2);

#5. Who spend more subscribed or non-subscribed? Compare average spend and total revenue between subscribers and non-subscribers
SELECT count(customer_id) as no_of_customers, subscription_status, round(avg(purchase_amount),2) as average_spend, sum(purchase_amount) as total_revenue FROM `e-commerce`.customer_shopping_trends group by subscription_status order by avg(purchase_amount), sum(purchase_amount);

#6. 5 products with highest % of purchase with discount applied
SELECT item_purchased, round(100*sum(case when discount_applied = "Yes" then 1 else 0 end) / count(*),2) as discount_rate FROM `e-commerce`.customer_shopping_trends group by item_purchased order by round(100*sum(case when discount_applied = "Yes" then 1 else 0 end) / count(*),2) desc limit 5;

#7. segment customers into New, Returning and Loyal based on their total no of purchases along with count
with customer_group as (select customer_id, previous_purchases, case when previous_purchases < 2 then 'New' when previous_purchases between 3 and 10 then 'Returning' else 'Loyal' end as customer_segment from `e-commerce`.customer_shopping_trends)
SELECT customer_segment, count(*) as no_of_customers FROM customer_group group by customer_segment;

#8. Top 3 most purchased product within each category
with product_count as (select item_purchased, category, count(customer_id) as total_orders, row_number()over (partition by category order by count(customer_id)) as product_rank FROM `e-commerce`.customer_shopping_trends group by category, item_purchased)
SELECT product_rank, category, item_purchased FROM product_count where product_rank <= 3;

#9. Customers who are repeat buyers are likely to subscribe
SELECT count(customer_id) as customer_count, subscription_status FROM `e-commerce`.customer_shopping_trends where previous_purchases > 2 group by subscription_status;

#10. Revenue contribution of each age group
SELECT sum(purchase_amount) as revenue, age_group FROM `e-commerce`.customer_shopping_trends group by age_group;